name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no deployuser@206.189.63.84 << 'EOF'

            source ~/.bashrc
            echo "Current path: $(pwd)"
            echo "Checking npm version: $(npm -v)"
            echo "Checking pm2 version: $(pm2 -v)"
            
            cd /home/deployuser/vulncontrol
            
            git pull origin main
            
            npm install
            
            cp /home/deployuser/envs/ui/.env /home/deployuser/vulncontrol/ui/.env
            cp /home/deployuser/envs/server/.env /home/deployuser/vulncontrol/server/.env
            
            npm run build
            
            cp -r dist/* /var/www/vulncontrol

            pm2 restart vulncontrol-server
            systemctl restart nginx
          EOF
