name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=deployuser@206.189.63.84 << 'EOF'
            
            cd /home/deployuser/vulncontrol
            
            git pull origin main
            
            npm install
            
            cp /home/deployuser/envs/ui/.env /home/deployuser/vulncontrol/ui/.env
            cp /home/deployuser/envs/server/.env /home/deployuser/vulncontrol/server/.env
            
            npm run build
            
            cp -r dist/* /var/www/vulncontrol

            pm2 restart vulncontrol-server
            sudo systemctl restart nginx
          EOF


# ssh -o StrictHostKeyChecking=no deployuser@your-droplet-ip << 'EOF'
#   cd /home/deployuser/vulncontrol
#   git pull origin main
#   npm install
#   npm run build
#   cp -r dist/* /var/www/vulncontrol
#   cp /home/deployuser/vulncontrol/.env /path/to/your/server/directory/.env
#   pm2 restart your-app
#   sudo systemctl restart nginx
# EOF
