name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no user@your-droplet-ip << 'EOF'
            # Navigate to the project directory
            cd ~/vulncontrol
            
            git pull origin main
            
            npm install
            
            npm run build

            cp ~/envs/ui/.env ~/vulncontrol/ui/.env
            cp ~/envs/server/.env ~/vulncontrol/server/.env
            
            cp -r dist/* /var/www/vulncontrol

            pm2 restart vulncontrol-server
            sudo systemctl restart nginx
          EOF
