name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no deployuser@${{ secrets.SERVER_IP }} << 'ENDSSH'
            # Load NVM and environment variables
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            source ~/.bashrc
            
            echo "Current path: $(pwd)"
            
            # Navigate to the UI directory and install dependencies
            cd /home/deployuser/vulncontrol/ui
            npm install
            
            # Navigate to the Server directory and install dependencies
            cd /home/deployuser/vulncontrol/server
            npm install
            
            # Copy environment files
            cp /home/deployuser/envs/ui/.env /home/deployuser/vulncontrol/ui/.env
            cp /home/deployuser/envs/server/.env /home/deployuser/vulncontrol/server/.env
            
            # Build the project
            cd /home/deployuser/vulncontrol/ui
            npm run build
            
            # Copy dist files with sudo (using echo to pass password to sudo)
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S cp -r dist/* /var/www/vulncontrol/
            
            # Restart services with sudo (using echo to pass password to sudo)
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S pm2 restart vulncontrol-server
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx
          ENDSSH


