name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no deployuser@${{ secrets.SERVER_IP }} << 'ENDSSH'
            # Load NVM and environment variables
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            source ~/.bashrc
            
            echo "Current path: $(pwd)"

            cd /home/deployuser/vulncontrol
            git pull origin main
            
            cd /home/deployuser/vulncontrol/ui
            npm install
            
            cd /home/deployuser/vulncontrol/server
            npm install
            
            cp /home/deployuser/envs/ui/.env /home/deployuser/vulncontrol/ui/.env
            cp /home/deployuser/envs/server/.env /home/deployuser/vulncontrol/server/.env
            
            cd /home/deployuser/vulncontrol/ui
            npm run build
            
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S cp -r dist/* /var/www/vulncontrol/
            
            # echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S pm2 restart index
            # echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S /home/deployuser/.nvm/versions/node/v22.11.0/bin/pm2 restart index
            pm2 restart vc
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx
          ENDSSH


